# Generated by Django 2.2.28 on 2024-10-29 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20241029_0948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-posted'], 'verbose_name': 'статья блога', 'verbose_name_plural': 'статьи блога'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 10, 29, 13, 52, 21, 460458), verbose_name='Опубликована'),
        ),
        migrations.AlterModelTable(
            name='blog',
            table='Posts',
        ),
    ]
